openapi: 3.0.1
info:
  title: MailAttachment
  description: API Definition of MailAttachment
  version: 1.0.0
servers:
- url: http://localhost:8290/mail
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
